### ISSUE TITLE
FreeAgent Not Getting an Authorisation Key.

### ISSUE THREAD

**Issue by danielpointondeveloping** [thoughtco/Freeagent-PHP#9]
Hi, I'm trying to use this API in order to get interact with free agent API. I've used the helper class in order to generate an auth url and do oauth, but when trying to use getAccessToken I get null, I am modifying the example here to try and get it to function. 

`$base_url = ( isset($_SERVER['HTTPS']) && $_SERVER['HTTPS']=='on' ? 'https' : 'http' ) . '://' .  $_SERVER['HTTP_HOST'];
  $url = $base_url . $_SERVER["REQUEST_URI"];
  	$client = new Freeagent($vars['id'], $vars['secret']);

  	// no OAuth code set
  	if (!isset($_GET['code'])){
    $base_url = ( isset($_SERVER['HTTPS']) && $_SERVER['HTTPS']=='on' ? 'https' : 'http' ) . '://' .  $_SERVER['HTTP_HOST'];
    $url = $base_url . $_SERVER["REQUEST_URI"];
  		// get the authorisation url we need to pass customer to, passing the url you want them returned to (This url)
  		$authoriseURL = $client->getAuthoriseURL($url);
          #Redirect User
      echo('<script>window.location="'.$authoriseURL.'";</script>');

  	// we have a code
  	} else {

  		// now exchange the code for an access token - you should save this for future usage
  		$accessToken = $client->getAccessToken($_GET['code'], $url);
  		// set authentication token
  		$client->setAccessToken($accessToken->access_token);`

 I looked into the getAccessToken function to see what is going wrong:

`   
 public function getAccessToken($code, $callback){

        // params to send to oauth receiver
        $params = array(
            'code' => $code,
            'grant_type' => 'authorization_code',
            'redirect_uri' => $callback
        );

        // call oauth
        $result = $this->call('', 'oauth', $params);

        // Save accessToken
        $this->accessToken = $result->access_token;

        // Return the response as an array
        return $result;
    }`

And when I added in a line of code to var_dump $result, I got null.
What's going wrong?
I have tried adding in a certificate, for some reason the curl request continues to fail

**Comment by ryanmitchell** [comment]
Did you do a dump after $this->call('', 'oauth', $params) ? It may be that the attribute isn't called access_token any more which would explain the null return from the overall function.

**Comment by danielpointondeveloping** [comment]
I just dumped $result post call, so theoretically the attribute name doesn't make a difference as $result was empty.

**Comment by ryanmitchell** [comment]
Yeah it shouldn't.

Did you dig any deeper into the call() function? Doing a dump of  $this->result around line 223 could yield some answers.

**Comment by danielpointondeveloping** [comment]
Hi, I just dumped $this->result and I got the result (bool)false, I'm fairly certain it's meant to be a string at this stage. I'm not entirely sure what to infer from this so any help would be appreciated, I'm only 15 so I'm pretty clueless with complicated scripts like these.

**Comment by ryanmitchell** [comment]
Sorry, the line should have been 233. happy to try and help if I can.

**Comment by danielpointondeveloping** [comment]
$this->result on line 233 is an empty string

**Comment by ryanmitchell** [comment]
Ok - try turning on debugging - set line #35 to true.

See if that gives you anything further.

**Comment by danielpointondeveloping** [comment]
I've got a lot of information from the $this->info variable, what should I be looking for?

**Comment by ryanmitchell** [comment]
I’m not sure entirely - if you can copy paste it here then it might give us something.

**Comment by danielpointondeveloping** [comment]
`{  
   [  
      "url"
   ]   => string(51) "https://api.sandbox.freeagent.com/v2/token_endpoint"   [  
      "content_type"
   ]   => NULL   [  
      "http_code"
   ]   => int(0)   [  
      "header_size"
   ]   => int(0)   [  
      "request_size"
   ]   => int(0)   [  
      "filetime"
   ]   => int(-1)   [  
      "ssl_verify_result"
   ]   => int(1)   [  
      "redirect_count"
   ]   => int(0)   [  
      "total_time"
   ]   => float(0.05031)   [  
      "namelookup_time"
   ]   => float(0.029338)   [  
      "connect_time"
   ]   => float(0.050294)   [  
      "pretransfer_time"
   ]   => float(0)   [  
      "size_upload"
   ]   => float(0)   [  
      "size_download"
   ]   => float(0)   [  
      "speed_download"
   ]   => float(0)   [  
      "speed_upload"
   ]   => float(0)   [  
      "download_content_length"
   ]   => float(-1)   [  
      "upload_content_length"
   ]   => float(-1)   [  
      "starttransfer_time"
   ]   => float(0)   [  
      "redirect_time"
   ]   => float(0)   [  
      "redirect_url"
   ]   => string(0) ""   [  
      "primary_ip"
   ]   => string(13) "109.73.126.98"   [  
      "certinfo"
   ]`

**Comment by ryanmitchell** [comment]
It looks like something on your server side is preventing the connection to that URL-  basically the connection to the token_endpoint url is failing.

**Comment by danielpointondeveloping** [comment]
Hi Ryan, 
If the issue is CURL related(which it is given that the server side connection is failing), could it be related to the .pem(certificate) file?

**Comment by danielpointondeveloping** [comment]
I just tested file_exists('/../cacert.pem') and the response was false, should I modify the path?

**Comment by ryanmitchell** [comment]
Yeah it could be - certainly worth commenting it out and seeing if it helps.

**Comment by danielpointondeveloping** [comment]
Didn't work unfortunately, I tried downloading the certificate file and placing it in the same folder as the PHP script and I got roughly the same information.

**Comment by ryanmitchell** [comment]
Try changing line #162 to a full path to the .pem file

**Comment by danielpointondeveloping** [comment]
Already tried that, I did notice one thing. ["namelookup_time"]=> float(4.1E-5) , that seems like too quick a lookup time for an office server, could it be a DNS issue?

**Comment by ryanmitchell** [comment]
I think thats just indicative of the issue being on the server side - there could be lots of reasons fro it.

Is CURL definitely enabled on the server?

**Comment by danielpointondeveloping** [comment]
Just checked the AMPPS config settings, the CURL.so library is included

**Comment by ryanmitchell** [comment]
Ok - it does seem to be something specific to your configuration I’m afraid.

Let me know if you manage to get any further.

**Comment by danielpointondeveloping** [comment]
Thanks for all your help, sorry to have taken up so much of your time

**Comment by danielpointondeveloping** [comment]
Hi Ryan,
Thanks for all your help yesterday. 
It would appear I had a licensing issue which I was able to fix, unfortunately I now appear to be having a different issue, I was able to make a test request towards FreeAgent and receive a standard(expected) $this->info result, with the certificate working, but the result included an error:
This is the result
`object(stdClass)#319 (1) { ["errors"]=> object(stdClass)#317 (1) { ["error"]=> object(stdClass)#316 (1) { ["message"]=> string(85) "Malformed Authorization HTTP header. Should be of form "Authorization: Bearer TOKEN"" } } }`
When I ran $client->get('contacts')

**Comment by ryanmitchell** [comment]
No problem - glad you're getting somewhere!

Are you just running the example? it looks like the access token isnt being set correctly.

**Comment by danielpointondeveloping** [comment]
I am running a slightly modified version of the example, with the app ID and secret included, but nothing's changed, the app ID and secret are being parsed correctly because the freeagent redirect URL was able to correctly identify the owner of the app and app name.

**Comment by ryanmitchell** [comment]
If you do a var_dump of $accessToken on line 33 what does it give?

**Comment by danielpointondeveloping** [comment]
` 
  	$client = new Freeagent($vars['id'], $vars['secret'], true);

  	// no OAuth code set
  	if (!isset($_GET['code'])){
    $base_url = ( isset($_SERVER['HTTPS']) && $_SERVER['HTTPS']=='on' ? 'https' : 'http' ) . '://' .  $_SERVER['HTTP_HOST'];
    $url = $base_url . $_SERVER["REQUEST_URI"];
  		// get the authorisation url we need to pass customer to, passing the url you want them returned to (This url)
  		$authoriseURL = $client->getAuthoriseURL($url);

   echo('<script>window.location="'.$authoriseURL.'";</script>');


  	// we have a code
  	} else {

  		// now exchange the code for an access token - you should save this for future usage
  		$accessToken = $client->getAccessToken($_GET['code'], $url);

  		// set authentication token
  		$client->setAccessToken($accessToken->access_token);
      var_dump($client->get('contacts'));
      $control=new syncObject($client);
      $testCommand=['service'=>'freeagent','REST'=>'GET','resource'=>'contacts'];
  	}
`

**Comment by danielpointondeveloping** [comment]
Null

**Comment by ryanmitchell** [comment]
Ok - worth enabling debug and seeing whats being returned when getAccessToken is called.

**Comment by danielpointondeveloping** [comment]
It all seems fairly standard, and I just checked- curl isn't returning any errors. I think it's what's being passed in thats the issue

**Comment by ryanmitchell** [comment]
Sorry, I can’t really help diagnose without seeing whats being returned as I’m in the dark.

Not looking for errors - just what the response is in case the library has the wrong key name or some other issue.

**Comment by danielpointondeveloping** [comment]
array(26) { ["url"]=> string(51) "https://api.sandbox.freeagent.com/v2/token_endpoint" ["content_type"]=> string(24) "text/html; charset=utf-8" ["http_code"]=> int(401) ["header_size"]=> int(1215) ["request_size"]=> int(317) ["filetime"]=> int(-1) ["ssl_verify_result"]=> int(0) ["redirect_count"]=> int(0) ["total_time"]=> float(0.151568) ["namelookup_time"]=> float(0.001633) ["connect_time"]=> float(0.023416) ["pretransfer_time"]=> float(0.088751) ["size_upload"]=> float(398) ["size_download"]=> float(27) ["speed_download"]=> float(178) ["speed_upload"]=> float(2625) ["download_content_length"]=> float(-1) ["upload_content_length"]=> float(398) ["starttransfer_time"]=> float(0.103296) ["redirect_time"]=> float(0) ["redirect_url"]=> string(0) "" ["primary_ip"]=> string(13) "109.73.126.98"  } ["primary_port"]=> int(443) ["local_ip"]=> string(13) "192.168.1.166" ["local_port"]=> int(55688) } string(0) ""
I've removed the certificate info for obvious reasons

**Comment by ryanmitchell** [comment]
cheers - what about the $this->result string?

**Comment by danielpointondeveloping** [comment]
string(27) "HTTP Basic: Access denied. "

**Comment by ryanmitchell** [comment]
Yeah it looks like something has changed on FreeAgent’s side.

I’m not sure I can help any - if you can figure it out open a Pull Request and I’ll happily update the library.

**Comment by danielpointondeveloping** [comment]
Hi Ryan,
I managed to fix the problem with [this](https://outlandish.com/blog/tutorial/freeagent-api-php-oauth2/) tutorial. I'm not entirely sure what the problem is, but the only difference I could see between the two was that the two specified different UA headers. 
Thanks for all your help
Best Wishes,
Daniel
